# Generated by Django 5.1.3 on 2024-11-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiphoneshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='CompareAtPrice',
            field=models.FloatField(max_length=50),
        ),
    ]
