# Generated by Django 5.1.3 on 2024-11-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiphoneshop', '0002_alter_variant_compareatprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='CompareAtPrice',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
